import type { FootballMatch } from "./football-utils";

const SOURCE_LABEL = "FIFA/Host city official schedule subset";
const SOURCE_CHECKED_AT = "2026-05-25";

export type WorldCupMatch = FootballMatch & {
  slug: string;
  stage: "Fase de grupos";
  group: string;
  homeFlag: string;
  awayFlag: string;
  venue: string;
  city: string;
  country: string;
  kickoffLabel: string;
  kickoffET: string;
  sourceLabel: typeof SOURCE_LABEL;
  sourceCheckedAt: typeof SOURCE_CHECKED_AT;
};

export const worldCup2026Matches: WorldCupMatch[] = [
  {
    id: "brazil-morocco-2026-06-13",
    slug: "brazil-morocco-2026-06-13",
    stage: "Fase de grupos",
    group: "Grupo C",
    groupCode: "Grupo C",
    homeTeam: { name: "Brazil", flagEmoji: "🇧🇷" },
    awayTeam: { name: "Morocco", flagEmoji: "🇲🇦" },
    homeFlag: "🇧🇷",
    awayFlag: "🇲🇦",
    venue: "NYNJ Stadium",
    venueName: "NYNJ Stadium",
    city: "East Rutherford, NJ",
    country: "United States",
    venueTimezone: "America/New_York",
    kickoffLabel: "Sat, Jun 13, 2026 · 6:00 PM ET",
    kickoffET: "2026-06-13 18:00 ET",
    kickoffUtc: "2026-06-13T22:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "spain-cabo-verde-2026-06-15",
    slug: "spain-cabo-verde-2026-06-15",
    stage: "Fase de grupos",
    group: "Grupo H",
    groupCode: "Grupo H",
    homeTeam: { name: "Spain", flagEmoji: "🇪🇸" },
    awayTeam: { name: "Cabo Verde", flagEmoji: "🇨🇻" },
    homeFlag: "🇪🇸",
    awayFlag: "🇨🇻",
    venue: "Atlanta Stadium",
    venueName: "Atlanta Stadium",
    city: "Atlanta, GA",
    country: "United States",
    venueTimezone: "America/New_York",
    kickoffLabel: "Mon, Jun 15, 2026 · 12:00 PM ET",
    kickoffET: "2026-06-15 12:00 ET",
    kickoffUtc: "2026-06-15T16:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "france-senegal-2026-06-16",
    slug: "france-senegal-2026-06-16",
    stage: "Fase de grupos",
    group: "Grupo I",
    groupCode: "Grupo I",
    homeTeam: { name: "France", flagEmoji: "🇫🇷" },
    awayTeam: { name: "Senegal", flagEmoji: "🇸🇳" },
    homeFlag: "🇫🇷",
    awayFlag: "🇸🇳",
    venue: "NYNJ Stadium",
    venueName: "NYNJ Stadium",
    city: "East Rutherford, NJ",
    country: "United States",
    venueTimezone: "America/New_York",
    kickoffLabel: "Tue, Jun 16, 2026 · 3:00 PM ET",
    kickoffET: "2026-06-16 15:00 ET",
    kickoffUtc: "2026-06-16T19:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "czechia-south-africa-2026-06-18",
    slug: "czechia-south-africa-2026-06-18",
    stage: "Fase de grupos",
    group: "Grupo A",
    groupCode: "Grupo A",
    homeTeam: { name: "Czechia", flagEmoji: "🇨🇿" },
    awayTeam: { name: "South Africa", flagEmoji: "🇿🇦" },
    homeFlag: "🇨🇿",
    awayFlag: "🇿🇦",
    venue: "Atlanta Stadium",
    venueName: "Atlanta Stadium",
    city: "Atlanta, GA",
    country: "United States",
    venueTimezone: "America/New_York",
    kickoffLabel: "Thu, Jun 18, 2026 · 12:00 PM ET",
    kickoffET: "2026-06-18 12:00 ET",
    kickoffUtc: "2026-06-18T16:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "scotland-brazil-2026-06-24",
    slug: "scotland-brazil-2026-06-24",
    stage: "Fase de grupos",
    group: "Grupo C",
    groupCode: "Grupo C",
    homeTeam: { name: "Scotland", flagEmoji: "🏴" },
    awayTeam: { name: "Brazil", flagEmoji: "🇧🇷" },
    homeFlag: "🏴",
    awayFlag: "🇧🇷",
    venue: "Miami Stadium",
    venueName: "Miami Stadium",
    city: "Miami Gardens, FL",
    country: "United States",
    venueTimezone: "America/New_York",
    kickoffLabel: "Wed, Jun 24, 2026 · 6:00 PM ET",
    kickoffET: "2026-06-24 18:00 ET",
    kickoffUtc: "2026-06-24T22:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "colombia-portugal-2026-06-27",
    slug: "colombia-portugal-2026-06-27",
    stage: "Fase de grupos",
    group: "Grupo K",
    groupCode: "Grupo K",
    homeTeam: { name: "Colombia", flagEmoji: "🇨🇴" },
    awayTeam: { name: "Portugal", flagEmoji: "🇵🇹" },
    homeFlag: "🇨🇴",
    awayFlag: "🇵🇹",
    venue: "Miami Stadium",
    venueName: "Miami Stadium",
    city: "Miami Gardens, FL",
    country: "United States",
    venueTimezone: "America/New_York",
    kickoffLabel: "Sat, Jun 27, 2026 · 7:30 PM ET",
    kickoffET: "2026-06-27 19:30 ET",
    kickoffUtc: "2026-06-27T23:30:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
];
