import type { FootballMatch } from "./football-utils";

const SOURCE_LABEL = "FIFA/Host city official schedule subset";
const SOURCE_CHECKED_AT = "2026-05-25";

export type WorldCupMatch = FootballMatch & {
  slug: string;
  stage: "Fase de grupos";
  group: string;
  homeFlag: string;
  awayFlag: string;
  venue: string;
  city: string;
  country: string;
  kickoffLabel: string;
  kickoffET: string;
  sourceLabel: typeof SOURCE_LABEL;
  sourceCheckedAt: typeof SOURCE_CHECKED_AT;
};

export const worldCup2026Matches: WorldCupMatch[] = [
  {
    id: "mexico-south-africa-2026-06-11",
    slug: "mexico-south-africa-2026-06-11",
    stage: "Fase de grupos",
    group: "Grupo A",
    groupCode: "Grupo A",
    homeTeam: { name: "México", flagEmoji: "🇲🇽" },
    awayTeam: { name: "Sudáfrica", flagEmoji: "🇿🇦" },
    homeFlag: "🇲🇽",
    awayFlag: "🇿🇦",
    venue: "Mexico City Stadium",
    venueName: "Mexico City Stadium",
    city: "Mexico City",
    country: "México",
    venueTimezone: "America/Mexico_City",
    kickoffLabel: "Jue, 11 Jun 2026 · 3:00 PM ET",
    kickoffET: "2026-06-11 15:00 ET",
    kickoffUtc: "2026-06-11T19:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "south-korea-czechia-2026-06-11",
    slug: "south-korea-czechia-2026-06-11",
    stage: "Fase de grupos",
    group: "Grupo A",
    groupCode: "Grupo A",
    homeTeam: { name: "Corea del Sur", flagEmoji: "🇰🇷" },
    awayTeam: { name: "Chequia", flagEmoji: "🇨🇿" },
    homeFlag: "🇰🇷",
    awayFlag: "🇨🇿",
    venue: "Mexico City Stadium",
    venueName: "Mexico City Stadium",
    city: "Mexico City",
    country: "México",
    venueTimezone: "America/Mexico_City",
    kickoffLabel: "Jue, 11 Jun 2026 · 10:00 PM ET",
    kickoffET: "2026-06-11 22:00 ET",
    kickoffUtc: "2026-06-12T02:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "canada-bosnia-and-herzegovina-2026-06-12",
    slug: "canada-bosnia-and-herzegovina-2026-06-12",
    stage: "Fase de grupos",
    group: "Grupo B",
    groupCode: "Grupo B",
    homeTeam: { name: "Canadá", flagEmoji: "🇨🇦" },
    awayTeam: { name: "Bosnia y Herzegovina", flagEmoji: "🇧🇦" },
    homeFlag: "🇨🇦",
    awayFlag: "🇧🇦",
    venue: "Toronto Stadium",
    venueName: "Toronto Stadium",
    city: "Toronto",
    country: "Canadá",
    venueTimezone: "America/Toronto",
    kickoffLabel: "Vie, 12 Jun 2026 · 3:00 PM ET",
    kickoffET: "2026-06-12 15:00 ET",
    kickoffUtc: "2026-06-12T19:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "usa-paraguay-2026-06-12",
    slug: "usa-paraguay-2026-06-12",
    stage: "Fase de grupos",
    group: "Grupo D",
    groupCode: "Grupo D",
    homeTeam: { name: "Estados Unidos", flagEmoji: "🇺🇸" },
    awayTeam: { name: "Paraguay", flagEmoji: "🇵🇾" },
    homeFlag: "🇺🇸",
    awayFlag: "🇵🇾",
    venue: "Los Angeles Stadium",
    venueName: "Los Angeles Stadium",
    city: "Los Angeles, CA",
    country: "Estados Unidos",
    venueTimezone: "America/Los_Angeles",
    kickoffLabel: "Vie, 12 Jun 2026 · 9:00 PM ET",
    kickoffET: "2026-06-12 21:00 ET",
    kickoffUtc: "2026-06-13T01:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "qatar-switzerland-2026-06-13",
    slug: "qatar-switzerland-2026-06-13",
    stage: "Fase de grupos",
    group: "Grupo B",
    groupCode: "Grupo B",
    homeTeam: { name: "Qatar", flagEmoji: "🇶🇦" },
    awayTeam: { name: "Suiza", flagEmoji: "🇨🇭" },
    homeFlag: "🇶🇦",
    awayFlag: "🇨🇭",
    venue: "San Francisco Bay Area Stadium",
    venueName: "San Francisco Bay Area Stadium",
    city: "Santa Clara, CA",
    country: "Estados Unidos",
    venueTimezone: "America/Los_Angeles",
    kickoffLabel: "Sáb, 13 Jun 2026 · 3:00 PM ET",
    kickoffET: "2026-06-13 15:00 ET",
    kickoffUtc: "2026-06-13T19:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "brazil-morocco-2026-06-13",
    slug: "brazil-morocco-2026-06-13",
    stage: "Fase de grupos",
    group: "Grupo C",
    groupCode: "Grupo C",
    homeTeam: { name: "Brasil", flagEmoji: "🇧🇷" },
    awayTeam: { name: "Marruecos", flagEmoji: "🇲🇦" },
    homeFlag: "🇧🇷",
    awayFlag: "🇲🇦",
    venue: "NYNJ Stadium",
    venueName: "NYNJ Stadium",
    city: "East Rutherford, NJ",
    country: "Estados Unidos",
    venueTimezone: "America/New_York",
    kickoffLabel: "Sáb, 13 Jun 2026 · 6:00 PM ET",
    kickoffET: "2026-06-13 18:00 ET",
    kickoffUtc: "2026-06-13T22:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "haiti-scotland-2026-06-13",
    slug: "haiti-scotland-2026-06-13",
    stage: "Fase de grupos",
    group: "Grupo C",
    groupCode: "Grupo C",
    homeTeam: { name: "Haití", flagEmoji: "🇭🇹" },
    awayTeam: { name: "Escocia", flagEmoji: "🏴" },
    homeFlag: "🇭🇹",
    awayFlag: "🏴",
    venue: "Boston Stadium",
    venueName: "Boston Stadium",
    city: "Foxborough, MA",
    country: "Estados Unidos",
    venueTimezone: "America/New_York",
    kickoffLabel: "Sáb, 13 Jun 2026 · 9:00 PM ET",
    kickoffET: "2026-06-13 21:00 ET",
    kickoffUtc: "2026-06-14T01:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "spain-cabo-verde-2026-06-15",
    slug: "spain-cabo-verde-2026-06-15",
    stage: "Fase de grupos",
    group: "Grupo H",
    groupCode: "Grupo H",
    homeTeam: { name: "España", flagEmoji: "🇪🇸" },
    awayTeam: { name: "Cabo Verde", flagEmoji: "🇨🇻" },
    homeFlag: "🇪🇸",
    awayFlag: "🇨🇻",
    venue: "Atlanta Stadium",
    venueName: "Atlanta Stadium",
    city: "Atlanta, GA",
    country: "Estados Unidos",
    venueTimezone: "America/New_York",
    kickoffLabel: "Lun, 15 Jun 2026 · 12:00 PM ET",
    kickoffET: "2026-06-15 12:00 ET",
    kickoffUtc: "2026-06-15T16:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "france-senegal-2026-06-16",
    slug: "france-senegal-2026-06-16",
    stage: "Fase de grupos",
    group: "Grupo I",
    groupCode: "Grupo I",
    homeTeam: { name: "Francia", flagEmoji: "🇫🇷" },
    awayTeam: { name: "Senegal", flagEmoji: "🇸🇳" },
    homeFlag: "🇫🇷",
    awayFlag: "🇸🇳",
    venue: "NYNJ Stadium",
    venueName: "NYNJ Stadium",
    city: "East Rutherford, NJ",
    country: "Estados Unidos",
    venueTimezone: "America/New_York",
    kickoffLabel: "Mar, 16 Jun 2026 · 3:00 PM ET",
    kickoffET: "2026-06-16 15:00 ET",
    kickoffUtc: "2026-06-16T19:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "czechia-south-africa-2026-06-18",
    slug: "czechia-south-africa-2026-06-18",
    stage: "Fase de grupos",
    group: "Grupo A",
    groupCode: "Grupo A",
    homeTeam: { name: "Chequia", flagEmoji: "🇨🇿" },
    awayTeam: { name: "Sudáfrica", flagEmoji: "🇿🇦" },
    homeFlag: "🇨🇿",
    awayFlag: "🇿🇦",
    venue: "Atlanta Stadium",
    venueName: "Atlanta Stadium",
    city: "Atlanta, GA",
    country: "Estados Unidos",
    venueTimezone: "America/New_York",
    kickoffLabel: "Jue, 18 Jun 2026 · 12:00 PM ET",
    kickoffET: "2026-06-18 12:00 ET",
    kickoffUtc: "2026-06-18T16:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "scotland-brazil-2026-06-24",
    slug: "scotland-brazil-2026-06-24",
    stage: "Fase de grupos",
    group: "Grupo C",
    groupCode: "Grupo C",
    homeTeam: { name: "Escocia", flagEmoji: "🏴" },
    awayTeam: { name: "Brasil", flagEmoji: "🇧🇷" },
    homeFlag: "🏴",
    awayFlag: "🇧🇷",
    venue: "Miami Stadium",
    venueName: "Miami Stadium",
    city: "Miami Gardens, FL",
    country: "Estados Unidos",
    venueTimezone: "America/New_York",
    kickoffLabel: "Mié, 24 Jun 2026 · 6:00 PM ET",
    kickoffET: "2026-06-24 18:00 ET",
    kickoffUtc: "2026-06-24T22:00:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
  {
    id: "colombia-portugal-2026-06-27",
    slug: "colombia-portugal-2026-06-27",
    stage: "Fase de grupos",
    group: "Grupo K",
    groupCode: "Grupo K",
    homeTeam: { name: "Colombia", flagEmoji: "🇨🇴" },
    awayTeam: { name: "Portugal", flagEmoji: "🇵🇹" },
    homeFlag: "🇨🇴",
    awayFlag: "🇵🇹",
    venue: "Miami Stadium",
    venueName: "Miami Stadium",
    city: "Miami Gardens, FL",
    country: "Estados Unidos",
    venueTimezone: "America/New_York",
    kickoffLabel: "Sáb, 27 Jun 2026 · 7:30 PM ET",
    kickoffET: "2026-06-27 19:30 ET",
    kickoffUtc: "2026-06-27T23:30:00.000Z",
    status: "scheduled",
    sourceLabel: SOURCE_LABEL,
    sourceCheckedAt: SOURCE_CHECKED_AT,
  },
];
